env: flex

entrypoint: gunicorn -b :$PORT app:app --timeout 400

resources:
  cpu: 4
  memory_gb: 6
  disk_size_gb: 20  # Increased disk size for better storage

# Remove handlers as Flexible Environment handles routing differently
