runtime: python312

entrypoint: gunicorn -b :$PORT app:app

instance_class: F4

automatic_scaling:
  min_instances: 1
  max_instances: 5

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

